# Vector container configuration
# Base image and third-party dependency versions

base_image: "${OS_IMAGE_BASE}:${OS_IMAGE_TAG}"
base_image_cache:
  - arg: OS_IMAGE_BASE
    source: alpine
    ghcr_repo: alpine-base
    tags: ["latest"]

build_args: {}
